In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from sklearn.ensemble import RandomForestClassifier
from imblearn.over_sampling import SMOTE

C:\Users\gautam yadav\AppData\Roaming\Python\Python311\site-packages\pandas\core\computation\expressions.py:22: UserWarning: Pandas requires version '2.10.2' or newer of 'numexpr' (version '2.8.7' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\gautam yadav\AppData\Roaming\Python\Python311\site-packages\pandas\core\arrays\masked.py:56: UserWarning: Pandas requires version '1.4.2' or newer of 'bottleneck' (version '1.3.7' currently installed).
  from pandas.core import (

In [2]:
data = pd.read_csv("C:\\Users\\gautam yadav\\OneDrive\\Desktop\\loan sytem\\utils\\customer_bank_details_data.csv")

In [3]:
df=pd.DataFrame(data)

In [4]:
df

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Term,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412,Short Term,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6,1,228190,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328,Short Term,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35,0,229976,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,0,Short Term,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666,Long Term,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9,0,256329,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220,Short Term,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15,0,253460,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89780,8506a4e9-af7d-47d2-a1bf-7ea2c41858f0,be67200e-1ef1-4b63-86a6-2bf27d3c704d,Fully Paid,210584,Short Term,719.0,783389.0,1 year,Home Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
89781,06eba04f-58fc-424a-b666-ed72aa008900,77f2252a-b7d1-4b07-a746-1202a8304290,Fully Paid,0,Short Term,732.0,1289416.0,1 year,Rent,Debt Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
89782,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,2ced5f10-bd60-4a11-9134-cadce4e7b0a3,Fully Paid,103136,Short Term,742.0,1150545.0,6 years,Rent,Debt Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0
89783,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,3e45ffda-99fd-4cfc-b8b8-446f4a505f36,Fully Paid,530332,Short Term,746.0,1717524.0,9 years,Rent,Debt Consolidation,9890.07,15.0,NaN,8,0,404225,738254.0,0.0,0.0
89784,c63916c6-6d46-47a9-949a-51d09af4414f,1b3014be-5c07-4d41-abe7-44573c375886,Fully Paid,0,Short Term,743.0,935180.0,NaN,Own Home,Debt Consolidation,9118.10,13.0,NaN,4,1,45600,91014.0,1.0,0.0

In [5]:
df = df[df['Current Loan Amount'] < 99999999]

In [6]:
df = df.drop('Term', axis=1)

In [7]:
bool_cols = df.select_dtypes(include='bool').columns
df[bool_cols] = df[bool_cols].astype(int)

In [8]:
df

,Loan ID,Customer ID,Loan Status,Current Loan Amount,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,14dd8831-6af5-400b-83ec-68e61888a048,981165ec-3274-42f5-a3b4-d104041a9ca9,Fully Paid,445412,709.0,1167493.0,8 years,Home Mortgage,Home Improvements,5214.74,17.2,NaN,6,1,228190,416746.0,1.0,0.0
1,4771cc26-131a-45db-b5aa-537ea4ba5342,2de017a3-2e01-49cb-a581-08169e83be29,Fully Paid,262328,NaN,NaN,10+ years,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35,0,229976,850784.0,0.0,0.0
2,4eed4e6a-aa2f-4c91-8651-ce984ee8fb26,5efb2b2b-bf11-4dfd-a572-3761a2694725,Fully Paid,0,741.0,2231892.0,8 years,Own Home,Debt Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
3,77598f7b-32e7-4e3b-a6e5-06ba0d98fe8a,e777faab-98ae-45af-9a86-7ce5b33b1011,Fully Paid,347666,721.0,806949.0,3 years,Own Home,Debt Consolidation,8741.90,12.0,NaN,9,0,256329,386958.0,0.0,0.0
4,d4062e70-befa-4995-8643-a0de73938182,81536ad9-5ccf-4eb8-befb-47a4d608658e,Fully Paid,176220,NaN,NaN,5 years,Rent,Debt Consolidation,20639.70,6.1,NaN,15,0,253460,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89780,8506a4e9-af7d-47d2-a1bf-7ea2c41858f0,be67200e-1ef1-4b63-86a6-2bf27d3c704d,Fully Paid,210584,719.0,783389.0,1 year,Home Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
89781,06eba04f-58fc-424a-b666-ed72aa008900,77f2252a-b7d1-4b07-a746-1202a8304290,Fully Paid,0,732.0,1289416.0,1 year,Rent,Debt Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
89782,e1cb4050-eff5-4bdb-a1b0-aabd3f7eaac7,2ced5f10-bd60-4a11-9134-cadce4e7b0a3,Fully Paid,103136,742.0,1150545.0,6 years,Rent,Debt Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0
89783,81ab928b-d1a5-4523-9a3c-271ebb01b4fb,3e45ffda-99fd-4cfc-b8b8-446f4a505f36,Fully Paid,530332,746.0,1717524.0,9 years,Rent,Debt Consolidation,9890.07,15.0,NaN,8,0,404225,738254.0,0.0,0.0
89784,c63916c6-6d46-47a9-949a-51d09af4414f,1b3014be-5c07-4d41-abe7-44573c375886,Fully Paid,0,743.0,935180.0,NaN,Own Home,Debt Consolidation,9118.10,13.0,NaN,4,1,45600,91014.0,1.0,0.0

In [9]:
# -------- DATA CLEANING --------

# Years in current job
if "Years in current job" in df.columns:
    df["Years in current job"] = df["Years in current job"].astype(str)
    df["Years in current job"] = df["Years in current job"].str.extract(r'(\d+)')
    df["Years in current job"] = pd.to_numeric(df["Years in current job"], errors="coerce").fillna(0)

# Term column (example: "36 months")
if "Term" in df.columns:
    df["Term"] = df["Term"].astype(str)
    df["Term"] = df["Term"].str.extract(r'(\d+)')
    df["Term"] = pd.to_numeric(df["Term"], errors="coerce").fillna(0)

In [10]:
df = df.drop(['Loan ID','Customer ID'], axis=1)

In [11]:
df.isnull().sum()

Loan Status                         0
Current Loan Amount                 0
Credit Score                    19154
Annual Income                   19154
Years in current job                0
Home Ownership                      0
Purpose                             0
Monthly Debt                        0
Years of Credit History             0
Months since last delinquent    48337
Number of Open Accounts             0
Number of Credit Problems           0
Current Credit Balance              0
Maximum Open Credit                 2
Bankruptcies                      190
Tax Liens                           9
dtype: int64

In [12]:
num_cols = [
    'Credit Score', 'Annual Income',
    'Months since last delinquent', 'Maximum Open Credit',
    'Tax Liens','Bankruptcies'

]

for col in num_cols:
    df[col] = df[col].fillna(df[col].median())

In [13]:
df

,Loan Status,Current Loan Amount,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,Fully Paid,445412,709.0,1167493.0,8.0,Home Mortgage,Home Improvements,5214.74,17.2,32.0,6,1,228190,416746.0,1.0,0.0
1,Fully Paid,262328,729.0,1168975.0,10.0,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35,0,229976,850784.0,0.0,0.0
2,Fully Paid,0,741.0,2231892.0,8.0,Own Home,Debt Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
3,Fully Paid,347666,721.0,806949.0,3.0,Own Home,Debt Consolidation,8741.90,12.0,32.0,9,0,256329,386958.0,0.0,0.0
4,Fully Paid,176220,729.0,1168975.0,5.0,Rent,Debt Consolidation,20639.70,6.1,32.0,15,0,253460,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89780,Fully Paid,210584,719.0,783389.0,1.0,Home Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
89781,Fully Paid,0,732.0,1289416.0,1.0,Rent,Debt Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
89782,Fully Paid,103136,742.0,1150545.0,6.0,Rent,Debt Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0
89783,Fully Paid,530332,746.0,1717524.0,9.0,Rent,Debt Consolidation,9890.07,15.0,32.0,8,0,404225,738254.0,0.0,0.0
89784,Fully Paid,0,743.0,935180.0,0.0,Own Home,Debt Consolidation,9118.10,13.0,32.0,4,1,45600,91014.0,1.0,0.0

In [14]:
df.isnull().sum()

Loan Status                     0
Current Loan Amount             0
Credit Score                    0
Annual Income                   0
Years in current job            0
Home Ownership                  0
Purpose                         0
Monthly Debt                    0
Years of Credit History         0
Months since last delinquent    0
Number of Open Accounts         0
Number of Credit Problems       0
Current Credit Balance          0
Maximum Open Credit             0
Bankruptcies                    0
Tax Liens                       0
dtype: int64

In [15]:
df

,Loan Status,Current Loan Amount,Credit Score,Annual Income,Years in current job,Home Ownership,Purpose,Monthly Debt,Years of Credit History,Months since last delinquent,Number of Open Accounts,Number of Credit Problems,Current Credit Balance,Maximum Open Credit,Bankruptcies,Tax Liens
0,Fully Paid,445412,709.0,1167493.0,8.0,Home Mortgage,Home Improvements,5214.74,17.2,32.0,6,1,228190,416746.0,1.0,0.0
1,Fully Paid,262328,729.0,1168975.0,10.0,Home Mortgage,Debt Consolidation,33295.98,21.1,8.0,35,0,229976,850784.0,0.0,0.0
2,Fully Paid,0,741.0,2231892.0,8.0,Own Home,Debt Consolidation,29200.53,14.9,29.0,18,1,297996,750090.0,0.0,0.0
3,Fully Paid,347666,721.0,806949.0,3.0,Own Home,Debt Consolidation,8741.90,12.0,32.0,9,0,256329,386958.0,0.0,0.0
4,Fully Paid,176220,729.0,1168975.0,5.0,Rent,Debt Consolidation,20639.70,6.1,32.0,15,0,253460,427174.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
89780,Fully Paid,210584,719.0,783389.0,1.0,Home Mortgage,Other,3727.61,17.4,18.0,6,0,456,259160.0,0.0,0.0
89781,Fully Paid,0,732.0,1289416.0,1.0,Rent,Debt Consolidation,13109.05,9.4,21.0,22,0,153045,509234.0,0.0,0.0
89782,Fully Paid,103136,742.0,1150545.0,6.0,Rent,Debt Consolidation,7315.57,18.8,18.0,12,1,109554,537548.0,1.0,0.0
89783,Fully Paid,530332,746.0,1717524.0,9.0,Rent,Debt Consolidation,9890.07,15.0,32.0,8,0,404225,738254.0,0.0,0.0
89784,Fully Paid,0,743.0,935180.0,0.0,Own Home,Debt Consolidation,9118.10,13.0,32.0,4,1,45600,91014.0,1.0,0.0

In [16]:
df['Loan Status'] = df['Loan Status'].map({
    'Fully Paid':0,
    'Charged Off':1
})

In [17]:
df = pd.get_dummies(df, columns=['Home Ownership','Purpose'])

In [18]:
X = df.drop(['Loan Status'] ,axis=1)

y = df['Loan Status']

In [19]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [20]:
import joblib
joblib.dump(X_train.columns.tolist(), "model_columns.pkl")

['model_columns.pkl']

In [21]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [22]:
from xgboost import XGBClassifier

model = XGBClassifier(scale_pos_weight=3)
model.fit(X_train, y_train)

XGBClassifier(base_score=None, booster=None, callbacks=None,
              colsample_bylevel=None, colsample_bynode=None,
              colsample_bytree=None, device=None, early_stopping_rounds=None,
              enable_categorical=False, eval_metric=None, feature_types=None,
              gamma=None, grow_policy=None, importance_type=None,
              interaction_constraints=None, learning_rate=None, max_bin=None,
              max_cat_threshold=None, max_cat_to_onehot=None,
              max_delta_step=None, max_depth=None, max_leaves=None,
              min_child_weight=None, missing=nan, monotone_constraints=None,
              multi_strategy=None, n_estimators=None, n_jobs=None,
              num_parallel_tree=None, random_state=None, ...)

In [23]:
from imblearn.over_sampling import SMOTE

sm = SMOTE()
X_train_res, y_train_res = sm.fit_resample(X_train, y_train)

In [24]:
y_prob = model.predict_proba(X_test)[:,1]

# Try different thresholds
y_pred = (y_prob > 0.57).astype(int)

# 4. Evaluation karo
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.83      0.83      0.83     13373
           1       0.49      0.49      0.49      4584

    accuracy                           0.74     17957
   macro avg       0.66      0.66      0.66     17957
weighted avg       0.74      0.74      0.74     17957

In [25]:
result = pd.DataFrame()

result["Actual"] = y_test
result["Prediction"] = y_pred
result["Probability"] = (y_prob * 100).round(2)  # percentage

In [26]:
result

       Actual  Prediction  Probability
65340       0           0    42.599998
53820       1           0    11.700000
53977       0           0    40.820000
16050       1           1    99.989998
36991       0           0    37.009998
...       ...         ...          ...
20130       0           1    68.919998
20106       0           0    11.500000
64254       0           0    46.709999
74536       1           1    61.990002
6597        1           0    49.590000

[17957 rows x 3 columns]

In [27]:
import joblib
joblib.dump(model, "loan_model.pkl")

['loan_model.pkl']